### ISSUE TITLE
Is there a sigmoid operator at the end of the decoder in the model?

### ISSUE THREAD

**Issue by XuLuo-ai** [HongtengXu/Relational-AutoEncoders#1]
Hello! It seems that the implementation on MNIST and CelebA does not include a **sigmoid** operator at the end of the decoder of the model, but on MNIST the sigmoid operator is cancelled as a comment. I have run your code along with all parameters in the paper. I find it coincides with the result of VAE in the paper when without sigmoid, but not wae\rae. Models with sigmoid all perform better. So is there a sigmoid operator in the decoder of the model?

**Comment by XuLuo-ai** [comment]
Hello! It seems that the implementation on MNIST and CelebA does not include a sigmoid operator at the end of the decoder in the model, and on MNIST the sigmoid operator is cancelled as a comment. I have run your code along with all parameters in the paper. I find it coincide with the result of VAE in the paper when without sigmoid, but not wae\rae. Models with sigmoid all perform better. So is there a sigmoid operator in the decoder of the model?

**Comment by HongtengXu** [comment]
> Hello! It seems that the implementation on MNIST and CelebA does not include a sigmoid operator at the end of the decoder in the model, and on MNIST the sigmoid operator is cancelled as a comment. I have run your code along with all parameters in the paper. I find it coincide with the result of VAE in the paper when without sigmoid, but not wae\rae. Models with sigmoid all perform better. So is there a sigmoid operator in the decoder of the model?

Hi, I implemented my models based on the architectures shown in "Wasserstein auto-encoder" https://arxiv.org/pdf/1711.01558.pdf, which did not apply sigmoid in the end. I also tried to apply sigmoid and got comparable or slightly better results. Feel free to change the architecture of the models. I think it doe not do harm to the functionality of the proposed regularizers.
